/**
 * Static mock property data. Used for SSG/static pages and client-side filtering.
 * Production: Replace with API client (e.g. fetch from your backend) or server-side data fetch.
 */
import type { Property } from "./types";

const PLACEHOLDER = "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80";
const PLACEHOLDER2 = "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80";
const PLACEHOLDER3 = "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80";
const PLACEHOLDER4 = "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80";
const PLACEHOLDER5 = "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80";
const PLACEHOLDER6 = "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "1",
    mode: "buy",
    title: "3 BHK Apartment in Sector 150",
    location: "Sector 150, Noida, Uttar Pradesh",
    city: "Noida",
    price: 12500000,
    currency: "INR",
    bhk: 3,
    areaSqFt: 1850,
    propertyType: "apartment",
    floorInfo: "12th of 18 floors",
    furnishing: "semi_furnished",
    listedBy: "owner",
    description: "Spacious 3 BHK with modern amenities, great connectivity to Delhi NCR. Near metro and schools.",
    amenities: ["lift", "parking", "security", "power_backup", "gym", "park"],
    badges: ["verified", "owner"],
    mainImageUrl: PLACEHOLDER,
    imageUrls: [PLACEHOLDER, PLACEHOLDER2, PLACEHOLDER3],
    createdAt: "2024-02-15T10:00:00Z",
  },
  {
    id: "2",
    mode: "rent",
    title: "2 BHK Apartment in DLF Phase 2",
    location: "DLF Phase 2, Gurgaon, Haryana",
    city: "Gurgaon",
    price: 35000,
    currency: "INR",
    bhk: 2,
    areaSqFt: 1200,
    propertyType: "apartment",
    floorInfo: "5th of 12 floors",
    furnishing: "furnished",
    listedBy: "agent",
    description: "Fully furnished 2 BHK with modular kitchen. Available immediately.",
    amenities: ["lift", "parking", "security", "gym", "clubhouse"],
    badges: ["verified", "new"],
    mainImageUrl: PLACEHOLDER2,
    imageUrls: [PLACEHOLDER2, PLACEHOLDER, PLACEHOLDER4],
    createdAt: "2024-02-20T09:00:00Z",
  },
  {
    id: "3",
    mode: "buy",
    title: "4 BHK Villa in Greater Noida",
    location: "Sector Omega 1, Greater Noida",
    city: "Greater Noida",
    price: 28500000,
    currency: "INR",
    bhk: 4,
    areaSqFt: 3200,
    propertyType: "house_villa",
    furnishing: "unfurnished",
    listedBy: "agent",
    description: "Luxury villa with private garden and premium finishes.",
    amenities: ["parking", "security", "power_backup", "park", "clubhouse"],
    badges: ["verified"],
    mainImageUrl: PLACEHOLDER4,
    imageUrls: [PLACEHOLDER4, PLACEHOLDER5, PLACEHOLDER],
    createdAt: "2024-02-10T14:00:00Z",
  },
  {
    id: "4",
    mode: "commercial",
    title: "Office Space in Connaught Place",
    location: "Connaught Place, New Delhi",
    city: "Delhi",
    price: 85000,
    currency: "INR",
    bhk: null,
    areaSqFt: 2200,
    propertyType: "commercial_office",
    floorInfo: "3rd of 8 floors",
    furnishing: "semi_furnished",
    listedBy: "agent",
    description: "Prime commercial office with central AC and reception area.",
    amenities: ["lift", "parking", "security", "power_backup"],
    badges: ["verified", "agent"],
    mainImageUrl: PLACEHOLDER5,
    imageUrls: [PLACEHOLDER5, PLACEHOLDER2],
    createdAt: "2024-02-18T11:00:00Z",
  },
  {
    id: "5",
    mode: "rent",
    title: "1 BHK Apartment in Sector 62",
    location: "Sector 62, Noida",
    city: "Noida",
    price: 18000,
    currency: "INR",
    bhk: 1,
    areaSqFt: 650,
    propertyType: "apartment",
    floorInfo: "2nd of 10 floors",
    furnishing: "unfurnished",
    listedBy: "owner",
    description: "Compact 1 BHK ideal for working professionals.",
    amenities: ["lift", "parking", "security"],
    badges: ["owner"],
    mainImageUrl: PLACEHOLDER6,
    imageUrls: [PLACEHOLDER6, PLACEHOLDER],
    createdAt: "2024-02-22T08:00:00Z",
  },
  {
    id: "6",
    mode: "buy",
    title: "Residential Plot in Sector 78",
    location: "Sector 78, Noida",
    city: "Noida",
    price: 4500000,
    currency: "INR",
    bhk: null,
    areaSqFt: 1200,
    propertyType: "plot",
    furnishing: "unfurnished",
    listedBy: "agent",
    description: "Freehold plot with clear title. Ready for construction.",
    amenities: [],
    badges: ["verified"],
    mainImageUrl: PLACEHOLDER3,
    imageUrls: [PLACEHOLDER3, PLACEHOLDER4],
    createdAt: "2024-02-12T16:00:00Z",
  },
  {
    id: "7",
    mode: "rent",
    title: "3 BHK Apartment in Saket",
    location: "Saket, South Delhi",
    city: "Delhi",
    price: 55000,
    currency: "INR",
    bhk: 3,
    areaSqFt: 1950,
    propertyType: "apartment",
    floorInfo: "7th of 15 floors",
    furnishing: "furnished",
    listedBy: "owner",
    description: "Premium 3 BHK with metro connectivity and mall nearby.",
    amenities: ["lift", "parking", "security", "gym", "clubhouse", "park"],
    badges: ["verified", "owner", "new"],
    mainImageUrl: PLACEHOLDER,
    imageUrls: [PLACEHOLDER, PLACEHOLDER2, PLACEHOLDER5],
    createdAt: "2024-02-25T09:00:00Z",
  },
  {
    id: "8",
    mode: "commercial",
    title: "Retail Shop in Mall of India",
    location: "Mall of India, Noida",
    city: "Noida",
    price: 120000,
    currency: "INR",
    bhk: null,
    areaSqFt: 800,
    propertyType: "shop",
    floorInfo: "Ground floor",
    furnishing: "unfurnished",
    listedBy: "agent",
    description: "High-footfall retail space in prominent mall.",
    amenities: ["lift", "parking", "security", "power_backup"],
    badges: ["agent"],
    mainImageUrl: PLACEHOLDER2,
    imageUrls: [PLACEHOLDER2, PLACEHOLDER6],
    createdAt: "2024-02-08T12:00:00Z",
  },
  {
    id: "9",
    mode: "buy",
    title: "2 BHK Apartment in Indirapuram",
    location: "Indirapuram, Ghaziabad",
    city: "Ghaziabad",
    price: 7200000,
    currency: "INR",
    bhk: 2,
    areaSqFt: 1100,
    propertyType: "apartment",
    floorInfo: "4th of 14 floors",
    furnishing: "semi_furnished",
    listedBy: "owner",
    description: "Well-maintained 2 BHK with good ventilation.",
    amenities: ["lift", "parking", "security", "park"],
    badges: ["owner"],
    mainImageUrl: PLACEHOLDER4,
    imageUrls: [PLACEHOLDER4, PLACEHOLDER],
    createdAt: "2024-02-05T10:00:00Z",
  },
  {
    id: "10",
    mode: "rent",
    title: "4 BHK Villa in Golf Course Road",
    location: "Golf Course Road, Gurgaon",
    city: "Gurgaon",
    price: 125000,
    currency: "INR",
    bhk: 4,
    areaSqFt: 3800,
    propertyType: "house_villa",
    furnishing: "furnished",
    listedBy: "agent",
    description: "Luxury villa with pool and landscaped garden.",
    amenities: ["parking", "security", "power_backup", "clubhouse", "gym", "park"],
    badges: ["verified", "agent", "new"],
    mainImageUrl: PLACEHOLDER5,
    imageUrls: [PLACEHOLDER5, PLACEHOLDER4, PLACEHOLDER6],
    createdAt: "2024-02-24T07:00:00Z",
  },
  {
    id: "11",
    mode: "buy",
    title: "3 BHK Apartment in Sector 18",
    location: "Sector 18, Noida",
    city: "Noida",
    price: 9800000,
    currency: "INR",
    bhk: 3,
    areaSqFt: 1650,
    propertyType: "apartment",
    floorInfo: "9th of 20 floors",
    furnishing: "unfurnished",
    listedBy: "agent",
    description: "Corner unit with extra balcony. Near sector 18 market.",
    amenities: ["lift", "parking", "security", "power_backup", "gym"],
    badges: ["verified", "agent"],
    mainImageUrl: PLACEHOLDER6,
    imageUrls: [PLACEHOLDER6, PLACEHOLDER2, PLACEHOLDER3],
    createdAt: "2024-02-14T13:00:00Z",
  },
  {
    id: "12",
    mode: "rent",
    title: "2 BHK in Cyber City",
    location: "Cyber City, Gurgaon",
    city: "Gurgaon",
    price: 42000,
    currency: "INR",
    bhk: 2,
    areaSqFt: 1050,
    propertyType: "apartment",
    floorInfo: "6th of 16 floors",
    furnishing: "semi_furnished",
    listedBy: "owner",
    description: "Walking distance to offices. Ideal for IT professionals.",
    amenities: ["lift", "parking", "security", "gym", "power_backup"],
    badges: ["owner", "new"],
    mainImageUrl: PLACEHOLDER,
    imageUrls: [PLACEHOLDER, PLACEHOLDER4],
    createdAt: "2024-02-26T10:00:00Z",
  },
  {
    id: "13",
    mode: "buy",
    title: "Residential Plot in Sohna Road",
    location: "Sohna Road, Gurgaon",
    city: "Gurgaon",
    price: 6200000,
    currency: "INR",
    bhk: null,
    areaSqFt: 1500,
    propertyType: "plot",
    furnishing: "unfurnished",
    listedBy: "agent",
    description: "Gated community plot with 24x7 security.",
    amenities: ["security", "park"],
    badges: ["verified"],
    mainImageUrl: PLACEHOLDER3,
    imageUrls: [PLACEHOLDER3],
    createdAt: "2024-02-01T15:00:00Z",
  },
  {
    id: "14",
    mode: "commercial",
    title: "Co-working Office in Nehru Place",
    location: "Nehru Place, New Delhi",
    city: "Delhi",
    price: 95000,
    currency: "INR",
    bhk: null,
    areaSqFt: 3500,
    propertyType: "commercial_office",
    floorInfo: "2nd of 6 floors",
    furnishing: "furnished",
    listedBy: "agent",
    description: "Fully furnished co-working space with meeting rooms.",
    amenities: ["lift", "parking", "security", "power_backup"],
    badges: ["verified", "agent", "new"],
    mainImageUrl: PLACEHOLDER5,
    imageUrls: [PLACEHOLDER5, PLACEHOLDER2, PLACEHOLDER6],
    createdAt: "2024-02-27T11:00:00Z",
  },
  {
    id: "15",
    mode: "rent",
    title: "1 BHK in Dwarka Sector 21",
    location: "Sector 21, Dwarka, Delhi",
    city: "Delhi",
    price: 22000,
    currency: "INR",
    bhk: 1,
    areaSqFt: 580,
    propertyType: "apartment",
    floorInfo: "3rd of 9 floors",
    furnishing: "unfurnished",
    listedBy: "owner",
    description: "Affordable 1 BHK near metro.",
    amenities: ["lift", "parking", "security"],
    badges: ["owner"],
    mainImageUrl: PLACEHOLDER2,
    imageUrls: [PLACEHOLDER2],
    createdAt: "2024-02-19T08:00:00Z",
  },
  // --- More house_villa (buy) - 5 more so villa+buy has 6 ---
  {
    id: "16",
    mode: "buy",
    title: "3 BHK Villa in Sector 50 Noida",
    location: "Sector 50, Noida, Uttar Pradesh",
    city: "Noida",
    price: 19500000,
    currency: "INR",
    bhk: 3,
    areaSqFt: 2600,
    propertyType: "house_villa",
    furnishing: "semi_furnished",
    listedBy: "owner",
    description: "Spacious villa with private lawn. Gated society with 24x7 security.",
    amenities: ["parking", "security", "power_backup", "park"],
    badges: ["verified", "owner"],
    mainImageUrl: PLACEHOLDER4,
    imageUrls: [PLACEHOLDER4, PLACEHOLDER5],
    createdAt: "2024-02-11T10:00:00Z",
  },
  {
    id: "17",
    mode: "buy",
    title: "5 BHK Luxury Villa in DLF Phase 5",
    location: "DLF Phase 5, Gurgaon",
    city: "Gurgaon",
    price: 42000000,
    currency: "INR",
    bhk: 5,
    areaSqFt: 4500,
    propertyType: "house_villa",
    furnishing: "unfurnished",
    listedBy: "agent",
    description: "Premium villa with pool, home theatre and servant room.",
    amenities: ["parking", "security", "power_backup", "clubhouse", "gym", "park"],
    badges: ["verified", "agent", "new"],
    mainImageUrl: PLACEHOLDER5,
    imageUrls: [PLACEHOLDER5, PLACEHOLDER4, PLACEHOLDER6],
    createdAt: "2024-02-23T09:00:00Z",
  },
  {
    id: "18",
    mode: "buy",
    title: "4 BHK Villa in Supertech Supernova",
    location: "Supertech Supernova, Noida",
    city: "Noida",
    price: 26500000,
    currency: "INR",
    bhk: 4,
    areaSqFt: 3100,
    propertyType: "house_villa",
    furnishing: "semi_furnished",
    listedBy: "agent",
    description: "Corner villa with terrace and garden. Ready to move.",
    amenities: ["parking", "security", "lift", "gym", "park"],
    badges: ["agent"],
    mainImageUrl: PLACEHOLDER,
    imageUrls: [PLACEHOLDER, PLACEHOLDER2],
    createdAt: "2024-02-07T14:00:00Z",
  },
  {
    id: "19",
    mode: "buy",
    title: "3 BHK Villa in Sohna Road",
    location: "Sohna Road, Gurgaon",
    city: "Gurgaon",
    price: 17800000,
    currency: "INR",
    bhk: 3,
    areaSqFt: 2400,
    propertyType: "house_villa",
    furnishing: "unfurnished",
    listedBy: "owner",
    description: "Independent villa with modern fittings. Near schools and hospitals.",
    amenities: ["parking", "security", "park"],
    badges: ["owner"],
    mainImageUrl: PLACEHOLDER2,
    imageUrls: [PLACEHOLDER2, PLACEHOLDER4],
    createdAt: "2024-02-16T11:00:00Z",
  },
  {
    id: "20",
    mode: "buy",
    title: "4 BHK Villa in Indirapuram",
    location: "Indirapuram, Ghaziabad",
    city: "Ghaziabad",
    price: 22800000,
    currency: "INR",
    bhk: 4,
    areaSqFt: 2950,
    propertyType: "house_villa",
    furnishing: "furnished",
    listedBy: "agent",
    description: "Fully furnished villa with modular kitchen. Quick possession.",
    amenities: ["parking", "security", "power_backup", "clubhouse", "park"],
    badges: ["verified", "agent"],
    mainImageUrl: PLACEHOLDER3,
    imageUrls: [PLACEHOLDER3, PLACEHOLDER5],
    createdAt: "2024-02-04T08:00:00Z",
  },
  // --- More house_villa (rent) - 5 more ---
  {
    id: "21",
    mode: "rent",
    title: "3 BHK Villa in Sector 72 Noida",
    location: "Sector 72, Noida",
    city: "Noida",
    price: 75000,
    currency: "INR",
    bhk: 3,
    areaSqFt: 2700,
    propertyType: "house_villa",
    furnishing: "semi_furnished",
    listedBy: "owner",
    description: "Villa available for family. Peaceful locality.",
    amenities: ["parking", "security", "park"],
    badges: ["owner"],
    mainImageUrl: PLACEHOLDER4,
    imageUrls: [PLACEHOLDER4],
    createdAt: "2024-02-13T10:00:00Z",
  },
  {
    id: "22",
    mode: "rent",
    title: "4 BHK Villa in DLF Phase 3",
    location: "DLF Phase 3, Gurgaon",
    city: "Gurgaon",
    price: 95000,
    currency: "INR",
    bhk: 4,
    areaSqFt: 3200,
    propertyType: "house_villa",
    furnishing: "furnished",
    listedBy: "agent",
    description: "Luxury villa on rent. Pool and garden included.",
    amenities: ["parking", "security", "power_backup", "gym", "park"],
    badges: ["verified", "agent"],
    mainImageUrl: PLACEHOLDER5,
    imageUrls: [PLACEHOLDER5, PLACEHOLDER6],
    createdAt: "2024-02-21T09:00:00Z",
  },
  {
    id: "23",
    mode: "rent",
    title: "3 BHK Villa in Greater Noida West",
    location: "Greater Noida West",
    city: "Greater Noida",
    price: 55000,
    currency: "INR",
    bhk: 3,
    areaSqFt: 2200,
    propertyType: "house_villa",
    furnishing: "unfurnished",
    listedBy: "owner",
    description: "Spacious villa at affordable rent. Near expressway.",
    amenities: ["parking", "security"],
    badges: ["owner", "new"],
    mainImageUrl: PLACEHOLDER,
    imageUrls: [PLACEHOLDER, PLACEHOLDER3],
    createdAt: "2024-02-28T07:00:00Z",
  },
  {
    id: "24",
    mode: "rent",
    title: "5 BHK Villa in Golf Course Road",
    location: "Golf Course Road, Gurgaon",
    city: "Gurgaon",
    price: 165000,
    currency: "INR",
    bhk: 5,
    areaSqFt: 4200,
    propertyType: "house_villa",
    furnishing: "furnished",
    listedBy: "agent",
    description: "Premium villa with pool, gym and landscaped garden.",
    amenities: ["parking", "security", "power_backup", "clubhouse", "gym", "park"],
    badges: ["verified", "agent"],
    mainImageUrl: PLACEHOLDER6,
    imageUrls: [PLACEHOLDER6, PLACEHOLDER4, PLACEHOLDER5],
    createdAt: "2024-02-09T12:00:00Z",
  },
  {
    id: "25",
    mode: "rent",
    title: "3 BHK Villa in Sector 137 Noida",
    location: "Sector 137, Noida",
    city: "Noida",
    price: 68000,
    currency: "INR",
    bhk: 3,
    areaSqFt: 2500,
    propertyType: "house_villa",
    furnishing: "semi_furnished",
    listedBy: "owner",
    description: "Independent villa with car parking. Available from next month.",
    amenities: ["parking", "security", "park"],
    badges: ["owner"],
    mainImageUrl: PLACEHOLDER2,
    imageUrls: [PLACEHOLDER2, PLACEHOLDER],
    createdAt: "2024-02-17T11:00:00Z",
  },
  {
    id: "26",
    mode: "rent",
    title: "4 BHK Villa in Faridabad Sector 28",
    location: "Sector 28, Faridabad",
    city: "Faridabad",
    price: 82000,
    currency: "INR",
    bhk: 4,
    areaSqFt: 3000,
    propertyType: "house_villa",
    furnishing: "furnished",
    listedBy: "agent",
    description: "Well-maintained villa with modern amenities.",
    amenities: ["parking", "security", "gym", "park"],
    badges: ["agent", "new"],
    mainImageUrl: PLACEHOLDER3,
    imageUrls: [PLACEHOLDER3],
    createdAt: "2024-02-25T08:00:00Z",
  },
  // --- More plot (buy) - 4 more ---
  {
    id: "27",
    mode: "buy",
    title: "Residential Plot in Sector 90 Noida",
    location: "Sector 90, Noida",
    city: "Noida",
    price: 5200000,
    currency: "INR",
    bhk: null,
    areaSqFt: 1350,
    propertyType: "plot",
    furnishing: "unfurnished",
    listedBy: "owner",
    description: "Freehold plot with clear title. Near proposed metro.",
    amenities: [],
    badges: ["owner"],
    mainImageUrl: PLACEHOLDER3,
    imageUrls: [PLACEHOLDER3, PLACEHOLDER4],
    createdAt: "2024-02-06T13:00:00Z",
  },
  {
    id: "28",
    mode: "buy",
    title: "Residential Plot in Greater Noida Sector 1",
    location: "Sector 1, Greater Noida",
    city: "Greater Noida",
    price: 3800000,
    currency: "INR",
    bhk: null,
    areaSqFt: 1100,
    propertyType: "plot",
    furnishing: "unfurnished",
    listedBy: "agent",
    description: "Affordable plot in developing area. Good appreciation potential.",
    amenities: ["security"],
    badges: ["verified", "agent"],
    mainImageUrl: PLACEHOLDER4,
    imageUrls: [PLACEHOLDER4],
    createdAt: "2024-02-19T10:00:00Z",
  },
  {
    id: "29",
    mode: "buy",
    title: "Residential Plot in Faridabad NIT",
    location: "NIT Faridabad",
    city: "Faridabad",
    price: 4800000,
    currency: "INR",
    bhk: null,
    areaSqFt: 1250,
    propertyType: "plot",
    furnishing: "unfurnished",
    listedBy: "owner",
    description: "Corner plot with road frontage. Clear documentation.",
    amenities: [],
    badges: ["owner"],
    mainImageUrl: PLACEHOLDER5,
    imageUrls: [PLACEHOLDER5],
    createdAt: "2024-02-14T09:00:00Z",
  },
  {
    id: "30",
    mode: "buy",
    title: "Residential Plot in Indirapuram",
    location: "Indirapuram, Ghaziabad",
    city: "Ghaziabad",
    price: 5500000,
    currency: "INR",
    bhk: null,
    areaSqFt: 1400,
    propertyType: "plot",
    furnishing: "unfurnished",
    listedBy: "agent",
    description: "Gated community plot. Ready for construction.",
    amenities: ["security", "park"],
    badges: ["verified"],
    mainImageUrl: PLACEHOLDER6,
    imageUrls: [PLACEHOLDER6, PLACEHOLDER3],
    createdAt: "2024-02-24T11:00:00Z",
  },
  {
    id: "31",
    mode: "buy",
    title: "Residential Plot in Dwarka Sector 23",
    location: "Sector 23, Dwarka, Delhi",
    city: "Delhi",
    price: 7200000,
    currency: "INR",
    bhk: null,
    areaSqFt: 1600,
    propertyType: "plot",
    furnishing: "unfurnished",
    listedBy: "agent",
    description: "Prime location plot. High demand area.",
    amenities: ["security"],
    badges: ["verified", "agent"],
    mainImageUrl: PLACEHOLDER,
    imageUrls: [PLACEHOLDER],
    createdAt: "2024-02-02T15:00:00Z",
  },
  // --- More commercial (office) - 4 more ---
  {
    id: "32",
    mode: "commercial",
    title: "Office Space in Sector 18 Noida",
    location: "Sector 18, Noida",
    city: "Noida",
    price: 72000,
    currency: "INR",
    bhk: null,
    areaSqFt: 1800,
    propertyType: "commercial_office",
    floorInfo: "5th of 12 floors",
    furnishing: "semi_furnished",
    listedBy: "agent",
    description: "Commercial office with cabin and workstations.",
    amenities: ["lift", "parking", "security", "power_backup"],
    badges: ["agent"],
    mainImageUrl: PLACEHOLDER5,
    imageUrls: [PLACEHOLDER5, PLACEHOLDER2],
    createdAt: "2024-02-11T10:00:00Z",
  },
  {
    id: "33",
    mode: "commercial",
    title: "Office in Cyber City Tower",
    location: "Cyber City, Gurgaon",
    city: "Gurgaon",
    price: 110000,
    currency: "INR",
    bhk: null,
    areaSqFt: 2800,
    propertyType: "commercial_office",
    floorInfo: "10th of 22 floors",
    furnishing: "furnished",
    listedBy: "owner",
    description: "Premium office space with panoramic view.",
    amenities: ["lift", "parking", "security", "power_backup", "gym"],
    badges: ["verified", "owner"],
    mainImageUrl: PLACEHOLDER2,
    imageUrls: [PLACEHOLDER2, PLACEHOLDER6],
    createdAt: "2024-02-20T09:00:00Z",
  },
  {
    id: "34",
    mode: "commercial",
    title: "Office Space in Saket",
    location: "Saket, South Delhi",
    city: "Delhi",
    price: 98000,
    currency: "INR",
    bhk: null,
    areaSqFt: 2400,
    propertyType: "commercial_office",
    floorInfo: "4th of 10 floors",
    furnishing: "semi_furnished",
    listedBy: "agent",
    description: "Commercial office near mall and metro.",
    amenities: ["lift", "parking", "security"],
    badges: ["verified", "agent", "new"],
    mainImageUrl: PLACEHOLDER6,
    imageUrls: [PLACEHOLDER6],
    createdAt: "2024-02-27T08:00:00Z",
  },
  {
    id: "35",
    mode: "commercial",
    title: "Office in DLF Cyber Park",
    location: "DLF Cyber Park, Gurgaon",
    city: "Gurgaon",
    price: 88000,
    currency: "INR",
    bhk: null,
    areaSqFt: 2000,
    propertyType: "commercial_office",
    floorInfo: "7th of 15 floors",
    furnishing: "unfurnished",
    listedBy: "owner",
    description: "Plug and play office space available.",
    amenities: ["lift", "parking", "security", "power_backup"],
    badges: ["owner"],
    mainImageUrl: PLACEHOLDER4,
    imageUrls: [PLACEHOLDER4, PLACEHOLDER5],
    createdAt: "2024-02-15T12:00:00Z",
  },
  {
    id: "36",
    mode: "commercial",
    title: "Office Space in Connaught Place Block B",
    location: "Connaught Place Block B, Delhi",
    city: "Delhi",
    price: 125000,
    currency: "INR",
    bhk: null,
    areaSqFt: 2600,
    propertyType: "commercial_office",
    floorInfo: "2nd of 6 floors",
    furnishing: "furnished",
    listedBy: "agent",
    description: "Prime CBD office with central AC.",
    amenities: ["lift", "parking", "security", "power_backup"],
    badges: ["verified", "agent"],
    mainImageUrl: PLACEHOLDER,
    imageUrls: [PLACEHOLDER, PLACEHOLDER3],
    createdAt: "2024-02-03T14:00:00Z",
  },
  {
    id: "37",
    mode: "commercial",
    title: "Office in Noida Sector 62",
    location: "Sector 62, Noida",
    city: "Noida",
    price: 65000,
    currency: "INR",
    bhk: null,
    areaSqFt: 1500,
    propertyType: "commercial_office",
    floorInfo: "3rd of 8 floors",
    furnishing: "unfurnished",
    listedBy: "owner",
    description: "Affordable office for startups and SMEs.",
    amenities: ["lift", "parking", "security"],
    badges: ["owner", "new"],
    mainImageUrl: PLACEHOLDER3,
    imageUrls: [PLACEHOLDER3],
    createdAt: "2024-02-26T10:00:00Z",
  },
  // --- More shop - 5 more ---
  {
    id: "38",
    mode: "commercial",
    title: "Retail Shop in Sector 18 Market",
    location: "Sector 18 Market, Noida",
    city: "Noida",
    price: 95000,
    currency: "INR",
    bhk: null,
    areaSqFt: 650,
    propertyType: "shop",
    floorInfo: "Ground floor",
    furnishing: "unfurnished",
    listedBy: "agent",
    description: "High visibility retail unit in busy market.",
    amenities: ["parking", "security"],
    badges: ["agent"],
    mainImageUrl: PLACEHOLDER2,
    imageUrls: [PLACEHOLDER2],
    createdAt: "2024-02-10T11:00:00Z",
  },
  {
    id: "39",
    mode: "commercial",
    title: "Shop in DLF Galleria",
    location: "DLF Galleria, Gurgaon",
    city: "Gurgaon",
    price: 145000,
    currency: "INR",
    bhk: null,
    areaSqFt: 900,
    propertyType: "shop",
    floorInfo: "Ground floor",
    furnishing: "unfurnished",
    listedBy: "owner",
    description: "Premium retail space in mall.",
    amenities: ["lift", "parking", "security", "power_backup"],
    badges: ["verified", "owner"],
    mainImageUrl: PLACEHOLDER6,
    imageUrls: [PLACEHOLDER6, PLACEHOLDER4],
    createdAt: "2024-02-22T09:00:00Z",
  },
  {
    id: "40",
    mode: "commercial",
    title: "Retail Unit in Saket Mall",
    location: "Select Citywalk, Saket",
    city: "Delhi",
    price: 165000,
    currency: "INR",
    bhk: null,
    areaSqFt: 750,
    propertyType: "shop",
    floorInfo: "1st floor",
    furnishing: "unfurnished",
    listedBy: "agent",
    description: "Branded mall location. High footfall.",
    amenities: ["lift", "parking", "security"],
    badges: ["verified", "agent", "new"],
    mainImageUrl: PLACEHOLDER4,
    imageUrls: [PLACEHOLDER4],
    createdAt: "2024-02-28T07:00:00Z",
  },
  {
    id: "41",
    mode: "commercial",
    title: "Shop in Indirapuram Market",
    location: "Indirapuram, Ghaziabad",
    city: "Ghaziabad",
    price: 55000,
    currency: "INR",
    bhk: null,
    areaSqFt: 500,
    propertyType: "shop",
    floorInfo: "Ground floor",
    furnishing: "unfurnished",
    listedBy: "owner",
    description: "Street-facing shop in residential area.",
    amenities: ["parking"],
    badges: ["owner"],
    mainImageUrl: PLACEHOLDER5,
    imageUrls: [PLACEHOLDER5],
    createdAt: "2024-02-08T13:00:00Z",
  },
  {
    id: "42",
    mode: "commercial",
    title: "Retail Space in Nehru Place",
    location: "Nehru Place, New Delhi",
    city: "Delhi",
    price: 78000,
    currency: "INR",
    bhk: null,
    areaSqFt: 600,
    propertyType: "shop",
    floorInfo: "Ground floor",
    furnishing: "semi_furnished",
    listedBy: "agent",
    description: "Ideal for electronics or services showroom.",
    amenities: ["lift", "parking", "security"],
    badges: ["agent"],
    mainImageUrl: PLACEHOLDER,
    imageUrls: [PLACEHOLDER],
    createdAt: "2024-02-16T10:00:00Z",
  },
  {
    id: "43",
    mode: "commercial",
    title: "Shop in Greater Noida Sector 2",
    location: "Sector 2, Greater Noida",
    city: "Greater Noida",
    price: 42000,
    currency: "INR",
    bhk: null,
    areaSqFt: 450,
    propertyType: "shop",
    floorInfo: "Ground floor",
    furnishing: "unfurnished",
    listedBy: "owner",
    description: "Affordable retail unit in growing area.",
    amenities: ["parking", "security"],
    badges: ["owner", "new"],
    mainImageUrl: PLACEHOLDER2,
    imageUrls: [PLACEHOLDER2],
    createdAt: "2024-02-24T08:00:00Z",
  },
  // --- More apartment (buy) - 3 more so we have 6+ ---
  {
    id: "44",
    mode: "buy",
    title: "4 BHK Apartment in Sector 100 Noida",
    location: "Sector 100, Noida",
    city: "Noida",
    price: 15800000,
    currency: "INR",
    bhk: 4,
    areaSqFt: 2200,
    propertyType: "apartment",
    floorInfo: "14th of 24 floors",
    furnishing: "semi_furnished",
    listedBy: "agent",
    description: "Luxury apartment with premium finishes.",
    amenities: ["lift", "parking", "security", "power_backup", "gym", "clubhouse", "park"],
    badges: ["verified", "agent", "new"],
    mainImageUrl: PLACEHOLDER3,
    imageUrls: [PLACEHOLDER3, PLACEHOLDER4],
    createdAt: "2024-02-21T09:00:00Z",
  },
  {
    id: "45",
    mode: "buy",
    title: "2 BHK Apartment in Dwarka Sector 19",
    location: "Sector 19, Dwarka, Delhi",
    city: "Delhi",
    price: 8200000,
    currency: "INR",
    bhk: 2,
    areaSqFt: 1050,
    propertyType: "apartment",
    floorInfo: "8th of 16 floors",
    furnishing: "unfurnished",
    listedBy: "owner",
    description: "Corner 2 BHK with good ventilation.",
    amenities: ["lift", "parking", "security"],
    badges: ["owner"],
    mainImageUrl: PLACEHOLDER6,
    imageUrls: [PLACEHOLDER6],
    createdAt: "2024-02-12T11:00:00Z",
  },
  {
    id: "46",
    mode: "buy",
    title: "3 BHK Apartment in Gurgaon Sector 54",
    location: "Sector 54, Gurgaon",
    city: "Gurgaon",
    price: 11200000,
    currency: "INR",
    bhk: 3,
    areaSqFt: 1750,
    propertyType: "apartment",
    floorInfo: "11th of 18 floors",
    furnishing: "semi_furnished",
    listedBy: "agent",
    description: "Ready to move 3 BHK with clubhouse access.",
    amenities: ["lift", "parking", "security", "gym", "park"],
    badges: ["verified", "agent"],
    mainImageUrl: PLACEHOLDER4,
    imageUrls: [PLACEHOLDER4, PLACEHOLDER5],
    createdAt: "2024-02-18T10:00:00Z",
  },
  // --- More apartment (rent) - 1 more so we have 6+ ---
  {
    id: "47",
    mode: "rent",
    title: "3 BHK Apartment in Noida Sector 76",
    location: "Sector 76, Noida",
    city: "Noida",
    price: 38000,
    currency: "INR",
    bhk: 3,
    areaSqFt: 1600,
    propertyType: "apartment",
    floorInfo: "6th of 14 floors",
    furnishing: "furnished",
    listedBy: "owner",
    description: "Fully furnished 3 BHK. Available immediately.",
    amenities: ["lift", "parking", "security", "gym"],
    badges: ["owner", "new"],
    mainImageUrl: PLACEHOLDER5,
    imageUrls: [PLACEHOLDER5],
    createdAt: "2024-02-27T12:00:00Z",
  },
];

/** Number of featured properties shown on home. */
export const FEATURED_COUNT = 6;

/** Precomputed featured list (avoids per-request slice). Production: replace with API. */
export const FEATURED_PROPERTIES: Property[] = MOCK_PROPERTIES.slice(0, FEATURED_COUNT);

/** O(1) lookup by id for property detail pages. Production: replace with API/database fetch. */
const PROPERTY_BY_ID = new Map<string, Property>(MOCK_PROPERTIES.map((p) => [p.id, p]));

export function getPropertyById(id: string): Property | undefined {
  return PROPERTY_BY_ID.get(id);
}
